name: include-what-you-use

on:
  pull_request:
    branches: ["main", "develop"]
jobs:
  include-what-you-use:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install missing software on debian/ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake clang make libcjson-dev
        sudo apt-get install -y iwyu

    - name: Prepare CMake
      run: |
        mkdir build
        cmake -S . -B build
      env:
        CC: clang
        CXX: clang++

    - name: iwyu_tool
      run: |
        iwyu_tool -p ./build/compile_commands.json -j $(nproc) -- -w -Xiwyu --max_line_length=1024  -Xiwyu --quoted_includes_first -Xiwyu --update_comments > iwyu.log

    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Compilation Database (include-what-you-use)
        path: ./build/compile_commands.json

    - uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: Logs (include-what-you-use)
        path: ./*.log
