name: Linter
on:
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: C/C++ code linter (clang-tidy, clang-format, and cppcheck)
        uses: ArtificialAmateur/cpp-linter-action@0.01
