name: prettier

on:
  pull_request:
    branches: ["main", "develop"]
jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prettify code
        uses: creyD/prettier_action@v4.6
        with:
          dry: True
          prettier_options: --check .
